services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=CloudFileStorage'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=1234'
    ports:
      - '5433:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
  minio:
    image: 'minio/minio:latest'
    environment:
      - 'MINIO_ROOT_USER=minio_user'
      - 'MINIO_ROOT_PASSWORD=minio_password'
      - 'MINIO_ADDRESS=:9000'
      - 'MINIO_CONSOLE_ADDRESS=:9001'
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    command: minio server /data
  backend:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
      - minio
      - redis

  frontend:
    image: cloud-frontend:1
    ports:
      - "80:80"
    depends_on:
      - backend

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  db-data:
  minio_data:
  redis_data:
